name: Test and build

on:
    pull_request: ~
    push:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            php: ['8.2', '8.3']
            mode: ['eab', 'default']
        steps:
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - uses: actions/checkout@v4

            - name: Install dependencies
              run: composer install --no-interaction --no-progress --ansi --prefer-stable
            - name: Run tests
              env:
                PHP_VERSION: ${{ matrix.php }}

              run: docker compose run --rm phpunit
